# Generated by Django 3.1.7 on 2021-02-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('battery_capacity', models.CharField(max_length=30)),
                ('power_max', models.IntegerField(max_length=5)),
                ('power_min', models.IntegerField(max_length=5)),
                ('soc', models.FloatField(max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Charger_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoeCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ipAddress', models.CharField(max_length=15)),
                ('power_max', models.IntegerField(max_length=5)),
                ('power_min', models.IntegerField(max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='posts', to='goeCharger_django.Charger_Category')),
                ('connected_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goeCharger_django.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='goeCharger_django.Car_Category'),
        ),
    ]
