# Generated by Django 3.1.7 on 2021-02-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goeCharger_django', '0003_auto_20210227_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='battery_capacity',
            field=models.IntegerField(),
        ),
    ]
