# Generated by Django 3.1.7 on 2021-03-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goeCharger_django', '0004_auto_20210227_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='goecharger',
            name='thread_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='categories',
            field=models.ManyToManyField(related_name='cars', to='goeCharger_django.Car_Category'),
        ),
        migrations.AlterField(
            model_name='goecharger',
            name='categories',
            field=models.ManyToManyField(related_name='goe_chargers', to='goeCharger_django.Charger_Category'),
        ),
    ]
