# Generated by Django 3.1.7 on 2021-03-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goeCharger_django', '0005_auto_20210303_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goecharger',
            old_name='connected_car',
            new_name='car_selected',
        ),
    ]
