# Generated by Django 3.1.7 on 2021-04-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goeCharger_django', '0006_auto_20210307_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoeChargerDailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('goeCharger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goeCharger_django.goecharger')),
            ],
        ),
    ]
